package application;

public enum attack_mode {
	ATTACK_MODE_STRAIGHT, 
	ATTACK_MODE_COMBI, 
	ATTACK_MODE_TOGGLE, 
	ATTACK_MODE_BF, 
	ATTACK_MODE_PERM, 
	ATTACK_MODE_TABLE, 
	ATTACK_MODE_HYBRID1, 
	ATTACK_MODE_HYBRID2, 
	ATTACK_MODE_NONE
}
