package application;

/**
     * Specifies choice of fallback strategy if matching cubin is not found.
     * Choice is based on supplied ::CUjit_fallback.  This option cannot be
     * used with cuLink* APIs as the linker requires exact matches.\n
     * Option type: unsigned int for enumerated type ::CUjit_fallback\n
     * Applies to: compiler only
     */
/**
     * Specifies whether to create debug information in output (-g)
     * (0: false, default)\n
     * Option type: int\n
     * Applies to: compiler and linker
     */
/**
     * Generate verbose log messages (0: false, default)\n
     * Option type: int\n
     * Applies to: compiler and linker
     */
/**
     * Generate line number information (-lineinfo) (0: false, default)\n
     * Option type: int\n
     * Applies to: compiler only
     */
/**
     * Specifies whether to enable caching explicitly (-dlcm) \n
     * Choice is based on supplied ::CUjit_cacheMode_enum.\n
     * Option type: unsigned int for enumerated type ::CUjit_cacheMode_enum\n
     * Applies to: compiler only
     */
/**
     * The below jit options are used for internal purposes only, in this version of CUDA
     */
/**
     * Array of device symbol names that will be relocated to the corresponing
     * host addresses stored in ::CU_JIT_GLOBAL_SYMBOL_ADDRESSES.\n
     * Must contain ::CU_JIT_GLOBAL_SYMBOL_COUNT entries.\n
     * When loding a device module, driver will relocate all encountered
     * unresolved symbols to the host addresses.\n
     * It is only allowed to register symbols that correspond to unresolved
     * global variables.\n
     * It is illegal to register the same device symbol at multiple addresses.\n
     * Option type: const char **\n
     * Applies to: dynamic linker only
     */
/**
     * Array of host addresses that will be used to relocate corresponding
     * device symbols stored in ::CU_JIT_GLOBAL_SYMBOL_NAMES.\n
     * Must contain ::CU_JIT_GLOBAL_SYMBOL_COUNT entries.\n
     * Option type: void **\n
     * Applies to: dynamic linker only
     */
/**
     * Number of entries in ::CU_JIT_GLOBAL_SYMBOL_NAMES and
     * ::CU_JIT_GLOBAL_SYMBOL_ADDRESSES arrays.\n
     * Option type: unsigned int\n
     * Applies to: dynamic linker only
     */
/**
 * Device properties
 */
public enum CUdevice_attribute_enum {
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK, 
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X, 
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y, 
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z, 
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X, 
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y, 
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z, 
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK, 
	CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK, 
	CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY, 
	CU_DEVICE_ATTRIBUTE_WARP_SIZE, 
	CU_DEVICE_ATTRIBUTE_MAX_PITCH, 
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK, 
	CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK, 
	CU_DEVICE_ATTRIBUTE_CLOCK_RATE, 
	CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT, 
	CU_DEVICE_ATTRIBUTE_GPU_OVERLAP, 
	CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT, 
	CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT, 
	CU_DEVICE_ATTRIBUTE_INTEGRATED, 
	CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY, 
	CU_DEVICE_ATTRIBUTE_COMPUTE_MODE, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES, 
	CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT, 
	CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS, 
	CU_DEVICE_ATTRIBUTE_ECC_ENABLED, 
	CU_DEVICE_ATTRIBUTE_PCI_BUS_ID, 
	CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID, 
	CU_DEVICE_ATTRIBUTE_TCC_DRIVER, 
	CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE, 
	CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH, 
	CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE, 
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR, 
	CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT, 
	CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE, 
	CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID, 
	CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT, 
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, 
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, 
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH, 
	CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR, 
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR, 
	CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY, 
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD, 
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID, 
	CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO, 
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS, 
	CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS, 
	CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM, 
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS, 
	CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS, 
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR, 
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH, 
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH, 
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN, 
	CU_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES, 
	CU_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED, 
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES, 
	CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST, 
	CU_DEVICE_ATTRIBUTE_MAX
}
