package application;

public enum CUjit_option_enum {
	CU_JIT_MAX_REGISTERS, 
	CU_JIT_THREADS_PER_BLOCK, 
	CU_JIT_WALL_TIME, 
	CU_JIT_INFO_LOG_BUFFER, 
	CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES, 
	CU_JIT_ERROR_LOG_BUFFER, 
	CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES, 
	CU_JIT_OPTIMIZATION_LEVEL, 
	CU_JIT_TARGET_FROM_CUCONTEXT, 
	CU_JIT_TARGET, 
	CU_JIT_FALLBACK_STRATEGY, 
	CU_JIT_GENERATE_DEBUG_INFO, 
	CU_JIT_LOG_VERBOSE, 
	CU_JIT_GENERATE_LINE_INFO, 
	CU_JIT_CACHE_MODE, 
	CU_JIT_NEW_SM3X_OPT, 
	CU_JIT_FAST_COMPILE, 
	CU_JIT_GLOBAL_SYMBOL_NAMES, 
	CU_JIT_GLOBAL_SYMBOL_ADDRESSES, 
	CU_JIT_GLOBAL_SYMBOL_COUNT, 
	CU_JIT_NUM_OPTIONS
}
/**
     * Max number of registers that a thread may use.\n
     * Option type: unsigned int\n
     * Applies to: compiler only
     */
