package application;

public enum guess_mode {
	GUESS_MODE_NONE, 
	GUESS_MODE_STRAIGHT_FILE, 
	GUESS_MODE_STRAIGHT_FILE_RULES_FILE, 
	GUESS_MODE_STRAIGHT_FILE_RULES_GEN, 
	GUESS_MODE_STRAIGHT_STDIN, 
	GUESS_MODE_STRAIGHT_STDIN_RULES_FILE, 
	GUESS_MODE_STRAIGHT_STDIN_RULES_GEN, 
	GUESS_MODE_COMBINATOR_BASE_LEFT, 
	GUESS_MODE_COMBINATOR_BASE_RIGHT, 
	GUESS_MODE_MASK, 
	GUESS_MODE_MASK_CS, 
	GUESS_MODE_HYBRID1, 
	GUESS_MODE_HYBRID1_CS, 
	GUESS_MODE_HYBRID2, 
	GUESS_MODE_HYBRID2_CS
}
