package application;

/**
 * hash category is relevant in usage.c (--help screen)
 */
public enum hash_category {
	HASH_CATEGORY_UNDEFINED, 
	HASH_CATEGORY_RAW_HASH, 
	HASH_CATEGORY_RAW_HASH_SALTED, 
	HASH_CATEGORY_RAW_HASH_AUTHENTICATED, 
	HASH_CATEGORY_RAW_CHECKSUM, 
	HASH_CATEGORY_RAW_CIPHER_KPA, 
	HASH_CATEGORY_GENERIC_KDF, 
	HASH_CATEGORY_NETWORK_PROTOCOL, 
	HASH_CATEGORY_OS, 
	HASH_CATEGORY_DATABASE_SERVER, 
	HASH_CATEGORY_NETWORK_SERVER, 
	HASH_CATEGORY_EAS, 
	HASH_CATEGORY_FDE, 
	HASH_CATEGORY_DOCUMENTS, 
	HASH_CATEGORY_PASSWORD_MANAGER, 
	HASH_CATEGORY_ARCHIVE, 
	HASH_CATEGORY_FORUM_SOFTWARE, 
	HASH_CATEGORY_OTP, 
	HASH_CATEGORY_PLAIN, 
	HASH_CATEGORY_FRAMEWORK
}
// hash specific
