package application;

// end original headers
public enum kern_type_luks {
	KERN_TYPE_LUKS_SHA1_AES, 
	KERN_TYPE_LUKS_SHA1_SERPENT, 
	KERN_TYPE_LUKS_SHA1_TWOFISH, 
	KERN_TYPE_LUKS_SHA256_AES, 
	KERN_TYPE_LUKS_SHA256_SERPENT, 
	KERN_TYPE_LUKS_SHA256_TWOFISH, 
	KERN_TYPE_LUKS_SHA512_AES, 
	KERN_TYPE_LUKS_SHA512_SERPENT, 
	KERN_TYPE_LUKS_SHA512_TWOFISH, 
	KERN_TYPE_LUKS_RIPEMD160_AES, 
	KERN_TYPE_LUKS_RIPEMD160_SERPENT, 
	KERN_TYPE_LUKS_RIPEMD160_TWOFISH, 
	KERN_TYPE_LUKS_WHIRLPOOL_AES, 
	KERN_TYPE_LUKS_WHIRLPOOL_SERPENT, 
	KERN_TYPE_LUKS_WHIRLPOOL_TWOFISH
}
