package application;

public enum opti_type {
	OPTI_TYPE_OPTIMIZED_KERNEL, 
	OPTI_TYPE_ZERO_BYTE, 
	OPTI_TYPE_PRECOMPUTE_INIT, 
	OPTI_TYPE_MEET_IN_MIDDLE, 
	OPTI_TYPE_EARLY_SKIP, 
	OPTI_TYPE_NOT_SALTED, 
	OPTI_TYPE_NOT_ITERATED, 
	OPTI_TYPE_PREPENDED_SALT, 
	OPTI_TYPE_APPENDED_SALT, 
	OPTI_TYPE_SINGLE_HASH, 
	OPTI_TYPE_SINGLE_SALT, 
	OPTI_TYPE_BRUTE_FORCE, 
	OPTI_TYPE_RAW_HASH, 
	OPTI_TYPE_SLOW_HASH_SIMD_INIT, 
	OPTI_TYPE_SLOW_HASH_SIMD_LOOP, 
	OPTI_TYPE_SLOW_HASH_SIMD_COMP, 
	OPTI_TYPE_USES_BITS_8, 
	OPTI_TYPE_USES_BITS_16, 
	OPTI_TYPE_USES_BITS_32, 
	OPTI_TYPE_USES_BITS_64
}
