package application;

public enum status_rc {
	STATUS_INIT, 
	STATUS_AUTOTUNE, 
	STATUS_SELFTEST, 
	STATUS_RUNNING, 
	STATUS_PAUSED, 
	STATUS_EXHAUSTED, 
	STATUS_CRACKED, 
	STATUS_ABORTED, 
	STATUS_QUIT, 
	STATUS_BYPASS, 
	STATUS_ABORTED_CHECKPOINT, 
	STATUS_ABORTED_RUNTIME, 
	STATUS_ERROR
}
