package application;

public enum token_attr {
	TOKEN_ATTR_FIXED_LENGTH, 
	TOKEN_ATTR_OPTIONAL_ROUNDS, 
	TOKEN_ATTR_VERIFY_SIGNATURE, 
	TOKEN_ATTR_VERIFY_LENGTH, 
	TOKEN_ATTR_VERIFY_DIGIT, 
	TOKEN_ATTR_VERIFY_FLOAT, 
	TOKEN_ATTR_VERIFY_HEX, 
	TOKEN_ATTR_VERIFY_BASE64A, 
	TOKEN_ATTR_VERIFY_BASE64B, 
	TOKEN_ATTR_VERIFY_BASE64C
}
