package application;

public enum vendor_id {
	VENDOR_ID_AMD, 
	VENDOR_ID_APPLE, 
	VENDOR_ID_INTEL_BEIGNET, 
	VENDOR_ID_INTEL_SDK, 
	VENDOR_ID_MESA, 
	VENDOR_ID_NV, 
	VENDOR_ID_POCL, 
	VENDOR_ID_AMD_USE_INTEL, 
	VENDOR_ID_GENERIC
}
