package application;

public enum cdio_dvd_book {
	CDIO_DVD_BOOK_DVD_ROM, 
	CDIO_DVD_BOOK_DVD_RAM, 
	CDIO_DVD_BOOK_DVD_R, 
	CDIO_DVD_BOOK_DVD_RW, 
	CDIO_DVD_BOOK_HD_DVD_ROM, 
	CDIO_DVD_BOOK_HD_DVD_RAM, 
	CDIO_DVD_BOOK_HD_DVD_R, 
	CDIO_DVD_BOOK_DVD_PRW, 
	CDIO_DVD_BOOK_DVD_PR, 
	CDIO_DVD_BOOK_DVD_PRW_DL, 
	CDIO_DVD_BOOK_DVD_PR_DL
}
