package application;

public enum action {
	ACTION_NONE, 
	ACTION_CONTINUE, 
	ACTION_SKIP, 
	ACTION_ABORT, 
	ACTION_QUIT, 
	ACTION_EDIT_TODO, 
	ACTION_SHOW_CURRENT_PATCH, 
	ACTION_SHORTEN_OIDS, 
	ACTION_EXPAND_OIDS, 
	ACTION_CHECK_TODO_LIST, 
	ACTION_REARRANGE_SQUASH, 
	ACTION_ADD_EXEC
}
