package application;

public enum color_diff {
	DIFF_RESET, 
	DIFF_CONTEXT, 
	DIFF_METAINFO, 
	DIFF_FRAGINFO, 
	DIFF_FILE_OLD, 
	DIFF_FILE_NEW, 
	DIFF_COMMIT, 
	DIFF_WHITESPACE, 
	DIFF_FUNCINFO, 
	DIFF_FILE_OLD_MOVED, 
	DIFF_FILE_OLD_MOVED_ALT, 
	DIFF_FILE_OLD_MOVED_DIM, 
	DIFF_FILE_OLD_MOVED_ALT_DIM, 
	DIFF_FILE_NEW_MOVED, 
	DIFF_FILE_NEW_MOVED_ALT, 
	DIFF_FILE_NEW_MOVED_DIM, 
	DIFF_FILE_NEW_MOVED_ALT_DIM, 
	DIFF_CONTEXT_DIM, 
	DIFF_FILE_OLD_DIM, 
	DIFF_FILE_NEW_DIM, 
	DIFF_CONTEXT_BOLD, 
	DIFF_FILE_OLD_BOLD, 
	DIFF_FILE_NEW_BOLD
}
