package application;

public enum color_wt_status {
	WT_STATUS_HEADER, 
	WT_STATUS_UPDATED, 
	WT_STATUS_CHANGED, 
	WT_STATUS_UNTRACKED, 
	WT_STATUS_NOBRANCH, 
	WT_STATUS_UNMERGED, 
	WT_STATUS_LOCAL_BRANCH, 
	WT_STATUS_REMOTE_BRANCH, 
	WT_STATUS_ONBRANCH, 
	WT_STATUS_MAXSLOT
}
