package application;

public enum decoration_type {
	DECORATION_NONE, 
	DECORATION_REF_LOCAL, 
	DECORATION_REF_REMOTE, 
	DECORATION_REF_TAG, 
	DECORATION_REF_STASH, 
	DECORATION_REF_HEAD, 
	DECORATION_GRAFTED
}
