package application;

public enum grep_color {
	GREP_COLOR_CONTEXT, 
	GREP_COLOR_FILENAME, 
	GREP_COLOR_FUNCTION, 
	GREP_COLOR_LINENO, 
	GREP_COLOR_COLUMNNO, 
	GREP_COLOR_MATCH_CONTEXT, 
	GREP_COLOR_MATCH_SELECTED, 
	GREP_COLOR_SELECTED, 
	GREP_COLOR_SEP, 
	NR_GREP_COLORS
}
