package application;

public enum notes_merge_strategy {
	NOTES_MERGE_RESOLVE_MANUAL, 
	NOTES_MERGE_RESOLVE_OURS, 
	NOTES_MERGE_RESOLVE_THEIRS, 
	NOTES_MERGE_RESOLVE_UNION, 
	NOTES_MERGE_RESOLVE_CAT_SORT_UNIQ
}
