package application;

public enum parse_opt_option_flags {
	PARSE_OPT_OPTARG, 
	PARSE_OPT_NOARG, 
	PARSE_OPT_NONEG, 
	PARSE_OPT_HIDDEN, 
	PARSE_OPT_LASTARG_DEFAULT, 
	PARSE_OPT_NODASH, 
	PARSE_OPT_LITERAL_ARGHELP, 
	PARSE_OPT_SHELL_EVAL, 
	PARSE_OPT_NOCOMPLETE, 
	PARSE_OPT_COMP_ARG
}
