package application;

public enum push_default_type {
	PUSH_DEFAULT_NOTHING, 
	PUSH_DEFAULT_MATCHING, 
	PUSH_DEFAULT_SIMPLE, 
	PUSH_DEFAULT_UPSTREAM, 
	PUSH_DEFAULT_CURRENT, 
	PUSH_DEFAULT_UNSPECIFIED
}
