package application;

public enum unpack_trees_error_types {
	ERROR_WOULD_OVERWRITE, 
	ERROR_NOT_UPTODATE_FILE, 
	ERROR_NOT_UPTODATE_DIR, 
	ERROR_WOULD_LOSE_UNTRACKED_OVERWRITTEN, 
	ERROR_WOULD_LOSE_UNTRACKED_REMOVED, 
	ERROR_BIND_OVERLAP, 
	ERROR_SPARSE_NOT_UPTODATE_FILE, 
	ERROR_WOULD_LOSE_ORPHANED_OVERWRITTEN, 
	ERROR_WOULD_LOSE_ORPHANED_REMOVED, 
	ERROR_WOULD_LOSE_SUBMODULE, 
	NB_UNPACK_TREES_ERROR_TYPES
}
