package application;

public enum wt_status_format {
	STATUS_FORMAT_NONE, 
	STATUS_FORMAT_LONG, 
	STATUS_FORMAT_SHORT, 
	STATUS_FORMAT_PORCELAIN, 
	STATUS_FORMAT_PORCELAIN_V2, 
	STATUS_FORMAT_UNSPECIFIED
}
