package application;

/* -LICENSE-START-
 ** Copyright (c) 2011 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 ** 
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 ** 
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */
// Interface ID Declarations
/* E5F693C1-4283-4716-B18F-C1431521955B */
/* 522A9E39-0F3C-4742-94EE-D80DE335DA1D */
/* Enum BMDDeckControlVTRControlState_v8_1 - VTR Control state */
public enum _BMDDeckControlVTRControlState_v8_1 {
	bmdDeckControlNotInVTRControlMode_v8_1, 
	bmdDeckControlVTRControlPlaying_v8_1, 
	bmdDeckControlVTRControlRecording_v8_1, 
	bmdDeckControlVTRControlStill_v8_1, 
	bmdDeckControlVTRControlSeeking_v8_1, 
	bmdDeckControlVTRControlStopped_v8_1
}
// call Release method to drop reference count
// call Release method to drop reference count
// BMD_DECKLINKAPI_v8_1_H
