package application;

public enum _BMDVideoInputConversionMode {
	bmdNoVideoInputConversion, 
	bmdVideoInputLetterboxDownconversionFromHD1080, 
	bmdVideoInputAnamorphicDownconversionFromHD1080, 
	bmdVideoInputLetterboxDownconversionFromHD720, 
	bmdVideoInputAnamorphicDownconversionFromHD720, 
	bmdVideoInputLetterboxUpconversion, 
	bmdVideoInputAnamorphicUpconversion
}
