package application;

public enum _D3DCMPFUNC {
	D3DCMP_NEVER, 
	D3DCMP_LESS, 
	D3DCMP_EQUAL, 
	D3DCMP_LESSEQUAL, 
	D3DCMP_GREATER, 
	D3DCMP_NOTEQUAL, 
	D3DCMP_GREATEREQUAL, 
	D3DCMP_ALWAYS, 
	D3DCMP_FORCE_DWORD
}
