package application;

public enum _D3DSTENCILOP {
	D3DSTENCILOP_KEEP, 
	D3DSTENCILOP_ZERO, 
	D3DSTENCILOP_REPLACE, 
	D3DSTENCILOP_INCRSAT, 
	D3DSTENCILOP_DECRSAT, 
	D3DSTENCILOP_INVERT, 
	D3DSTENCILOP_INCR, 
	D3DSTENCILOP_DECR, 
	D3DSTENCILOP_FORCE_DWORD
}
