package application;

public enum _D3DTRANSFORMSTATETYPE {
	D3DTS_VIEW, 
	D3DTS_PROJECTION, 
	D3DTS_TEXTURE0, 
	D3DTS_TEXTURE1, 
	D3DTS_TEXTURE2, 
	D3DTS_TEXTURE3, 
	D3DTS_TEXTURE4, 
	D3DTS_TEXTURE5, 
	D3DTS_TEXTURE6, 
	D3DTS_TEXTURE7, 
	D3DTS_FORCE_DWORD
}
