package application;

/* CubeMap Face identifiers */
public enum _D3DCUBEMAP_FACES {
	D3DCUBEMAP_FACE_POSITIVE_X, 
	D3DCUBEMAP_FACE_NEGATIVE_X, 
	D3DCUBEMAP_FACE_POSITIVE_Y, 
	D3DCUBEMAP_FACE_NEGATIVE_Y, 
	D3DCUBEMAP_FACE_POSITIVE_Z, 
	D3DCUBEMAP_FACE_NEGATIVE_Z, 
	D3DCUBEMAP_FACE_FORCE_DWORD
}
