package application;

/* Multi-Sample buffer types */
public enum _D3DMULTISAMPLE_TYPE {
	D3DMULTISAMPLE_NONE, 
	D3DMULTISAMPLE_2_SAMPLES, 
	D3DMULTISAMPLE_3_SAMPLES, 
	D3DMULTISAMPLE_4_SAMPLES, 
	D3DMULTISAMPLE_5_SAMPLES, 
	D3DMULTISAMPLE_6_SAMPLES, 
	D3DMULTISAMPLE_7_SAMPLES, 
	D3DMULTISAMPLE_8_SAMPLES, 
	D3DMULTISAMPLE_9_SAMPLES, 
	D3DMULTISAMPLE_10_SAMPLES, 
	D3DMULTISAMPLE_11_SAMPLES, 
	D3DMULTISAMPLE_12_SAMPLES, 
	D3DMULTISAMPLE_13_SAMPLES, 
	D3DMULTISAMPLE_14_SAMPLES, 
	D3DMULTISAMPLE_15_SAMPLES, 
	D3DMULTISAMPLE_16_SAMPLES, 
	D3DMULTISAMPLE_FORCE_DWORD
}
