package application;

/* Types */
public enum _D3DRESOURCETYPE {
	D3DRTYPE_SURFACE, 
	D3DRTYPE_VOLUME, 
	D3DRTYPE_TEXTURE, 
	D3DRTYPE_VOLUMETEXTURE, 
	D3DRTYPE_CUBETEXTURE, 
	D3DRTYPE_VERTEXBUFFER, 
	D3DRTYPE_INDEXBUFFER, 
	D3DRTYPE_FORCE_DWORD
}
