package application;

// same as D3DWRAP_U
// same as D3DWRAP_V
// same as D3DWRAP_W
/* Flags to construct D3DRS_COLORWRITEENABLE */
/*
 * State enumerants for per-stage texture processing.
 */
public enum _D3DTEXTURESTAGESTATETYPE {
	D3DTSS_COLOROP, 
	D3DTSS_COLORARG1, 
	D3DTSS_COLORARG2, 
	D3DTSS_ALPHAOP, 
	D3DTSS_ALPHAARG1, 
	D3DTSS_ALPHAARG2, 
	D3DTSS_BUMPENVMAT00, 
	D3DTSS_BUMPENVMAT01, 
	D3DTSS_BUMPENVMAT10, 
	D3DTSS_BUMPENVMAT11, 
	D3DTSS_TEXCOORDINDEX, 
	D3DTSS_ADDRESSU, 
	D3DTSS_ADDRESSV, 
	D3DTSS_BORDERCOLOR, 
	D3DTSS_MAGFILTER, 
	D3DTSS_MINFILTER, 
	D3DTSS_MIPFILTER, 
	D3DTSS_MIPMAPLODBIAS, 
	D3DTSS_MAXMIPLEVEL, 
	D3DTSS_MAXANISOTROPY, 
	D3DTSS_BUMPENVLSCALE, 
	D3DTSS_BUMPENVLOFFSET, 
	D3DTSS_TEXTURETRANSFORMFLAGS, 
	D3DTSS_ADDRESSW, 
	D3DTSS_COLORARG0, 
	D3DTSS_ALPHAARG0, 
	D3DTSS_RESULTARG, 
	D3DTSS_FORCE_DWORD
}
