package application;

public enum _D3DBLEND {
	D3DBLEND_ZERO, 
	D3DBLEND_ONE, 
	D3DBLEND_SRCCOLOR, 
	D3DBLEND_INVSRCCOLOR, 
	D3DBLEND_SRCALPHA, 
	D3DBLEND_INVSRCALPHA, 
	D3DBLEND_DESTALPHA, 
	D3DBLEND_INVDESTALPHA, 
	D3DBLEND_DESTCOLOR, 
	D3DBLEND_INVDESTCOLOR, 
	D3DBLEND_SRCALPHASAT, 
	D3DBLEND_BOTHSRCALPHA, 
	D3DBLEND_BOTHINVSRCALPHA, 
	D3DBLEND_FORCE_DWORD
}
