package application;

public enum _NV_ENC_STEREO_PACKING_MODE {
	NV_ENC_STEREO_PACKING_MODE_NONE, 
	NV_ENC_STEREO_PACKING_MODE_CHECKERBOARD, 
	NV_ENC_STEREO_PACKING_MODE_COLINTERLEAVE, 
	NV_ENC_STEREO_PACKING_MODE_ROWINTERLEAVE, 
	NV_ENC_STEREO_PACKING_MODE_SIDEBYSIDE, 
	NV_ENC_STEREO_PACKING_MODE_TOPBOTTOM, 
	NV_ENC_STEREO_PACKING_MODE_FRAMESEQ
}
