package application;

public enum _NV_ENC_PARAMS_RC_MODE {
	NV_ENC_PARAMS_RC_CONSTQP, 
	NV_ENC_PARAMS_RC_VBR, 
	NV_ENC_PARAMS_RC_CBR, 
	NV_ENC_PARAMS_RC_CBR_LOWDELAY_HQ, 
	NV_ENC_PARAMS_RC_CBR_HQ, 
	NV_ENC_PARAMS_RC_VBR_HQ
}
