package application;

public enum _NV_ENC_H264_BDIRECT_MODE {
	NV_ENC_H264_BDIRECT_MODE_AUTOSELECT, 
	NV_ENC_H264_BDIRECT_MODE_DISABLE, 
	NV_ENC_H264_BDIRECT_MODE_TEMPORAL, 
	NV_ENC_H264_BDIRECT_MODE_SPATIAL
}
