package application;

public enum _NV_ENC_H264_ADAPTIVE_TRANSFORM_MODE {
	NV_ENC_H264_ADAPTIVE_TRANSFORM_AUTOSELECT, 
	NV_ENC_H264_ADAPTIVE_TRANSFORM_DISABLE, 
	NV_ENC_H264_ADAPTIVE_TRANSFORM_ENABLE
}
