package application;

public enum _NV_ENC_INPUT_RESOURCE_TYPE {
	NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX, 
	NV_ENC_INPUT_RESOURCE_TYPE_CUDADEVICEPTR, 
	NV_ENC_INPUT_RESOURCE_TYPE_CUDAARRAY, 
	NV_ENC_INPUT_RESOURCE_TYPE_OPENGL_TEX
}
