package application;

/**
 * Input buffer formats
 */
public enum _NV_ENC_BUFFER_FORMAT {
	NV_ENC_BUFFER_FORMAT_UNDEFINED, 
	NV_ENC_BUFFER_FORMAT_NV12, 
	NV_ENC_BUFFER_FORMAT_YV12, 
	NV_ENC_BUFFER_FORMAT_IYUV, 
	NV_ENC_BUFFER_FORMAT_YUV444, 
	NV_ENC_BUFFER_FORMAT_YUV420_10BIT, 
	NV_ENC_BUFFER_FORMAT_YUV444_10BIT, 
	NV_ENC_BUFFER_FORMAT_ARGB, 
	NV_ENC_BUFFER_FORMAT_ARGB10, 
	NV_ENC_BUFFER_FORMAT_AYUV, 
	NV_ENC_BUFFER_FORMAT_ABGR, 
	NV_ENC_BUFFER_FORMAT_ABGR10
}
