package application;

public enum _NV_ENC_EMPHASIS_MAP_LEVEL {
	NV_ENC_EMPHASIS_MAP_LEVEL_0, 
	NV_ENC_EMPHASIS_MAP_LEVEL_1, 
	NV_ENC_EMPHASIS_MAP_LEVEL_2, 
	NV_ENC_EMPHASIS_MAP_LEVEL_3, 
	NV_ENC_EMPHASIS_MAP_LEVEL_4, 
	NV_ENC_EMPHASIS_MAP_LEVEL_5
}
