package application;

public enum _NV_ENC_PIC_TYPE {
	NV_ENC_PIC_TYPE_P, 
	NV_ENC_PIC_TYPE_B, 
	NV_ENC_PIC_TYPE_I, 
	NV_ENC_PIC_TYPE_IDR, 
	NV_ENC_PIC_TYPE_BI, 
	NV_ENC_PIC_TYPE_SKIPPED, 
	NV_ENC_PIC_TYPE_INTRA_REFRESH, 
	NV_ENC_PIC_TYPE_UNKNOWN
}
