package application;

public enum obs_hotkey_registerer_type {
	OBS_HOTKEY_REGISTERER_FRONTEND, 
	OBS_HOTKEY_REGISTERER_SOURCE, 
	OBS_HOTKEY_REGISTERER_OUTPUT, 
	OBS_HOTKEY_REGISTERER_ENCODER, 
	OBS_HOTKEY_REGISTERER_SERVICE
}
/* getter functions */
