package application;

public enum qsv_cpu_platform {
	QSV_CPU_PLATFORM_UNKNOWN, 
	QSV_CPU_PLATFORM_BNL, 
	QSV_CPU_PLATFORM_SNB, 
	QSV_CPU_PLATFORM_IVB, 
	QSV_CPU_PLATFORM_SLM, 
	QSV_CPU_PLATFORM_CHT, 
	QSV_CPU_PLATFORM_HSW, 
	QSV_CPU_PLATFORM_BDW, 
	QSV_CPU_PLATFORM_SKL, 
	QSV_CPU_PLATFORM_INTEL
}
